# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
android.builtInKotlin=false

# ACTIVAR ANDROIDX (Obligatorio para Compose)
android.useAndroidX=true
# Habilitar Jetifier para convertir librerías antiguas automáticamente
android.enableJetifier=true
